events {
  worker_connections 1024;
}

http {
  include mime.types;
  default_type application/octet-stream;

  upstream auth_service         { server auth-service:8082; }
  upstream user_service         { server user-service:8081; }
  upstream notification_service { server notification-service:8083; }
  upstream booking_service      { server booking-service:8084; }
  upstream parking_service      { server parking-service:8085; }
  upstream payment_service      { server payment-service:8086; }

  log_format main '$remote_addr - "$request" $status $body_bytes_sent';
  access_log /var/log/nginx/access.log main;

  server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header Host              $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;

    location / {
    try_files $uri $uri/ /index.html;
    }

    location = /api/auth { return 308 /api/auth/; }
    location ^~ /api/auth/ {
        proxy_pass http://auth_service/;
    }

    location = /api/users { return 308 /api/users/; }
    location ^~ /api/users/ {
        proxy_pass http://user_service/users/;
    }

    location = /api/notifications { return 308 /api/notifications/; }
    location ^~ /api/notifications/ {
        proxy_pass http://notification_service/notifications/;
    }

    location = /api/bookings { return 308 /api/bookings/; }
    location ^~ /api/bookings/ {
        proxy_pass http://booking_service/bookings/;
    }

    location = /api/parking { return 308 /api/parking/; }
    location ^~ /api/parking/ {
        proxy_pass http://parking_service/;
    }

    location = /api/payments { return 308 /api/payments/; }
    location ^~ /api/payments/ {
        proxy_pass http://payment_service/payments/;
    }
  }
}